### PR TITLE
Preliminary Haiku support

### PR DESCRIPTION
**Pull request by extrowerk**
Introduces basic support for Haiku (GCC5). Only minor patches required.

dig

### CODE REVIEW

**Comment by ensiform** [comment]
What GL driver is supported on the system? And what GPU are you currently using in the test screenshot.

**Comment by miqlas** [comment]
@ensiform: Haiku got currently only MESA based software render, but hardware 3D acceleration is one of the current gsoc task.
The GPU is Intel GMA 4500M HD.

**Comment by miqlas** [comment]
Any news here?

**Comment by Razish** [comment]
+1 good stuff :>

**Comment by miqlas** [comment]
Any news here?

**Comment by ensiform** [comment]
This could still be merged if it's functional

**Pull request closed without merging**
