### PR TITLE
Use system zlib headers if we're using system zlib

### PR DESCRIPTION
**Pull request by smcv**
As I mentioned on #604, distributions like Debian don't like using embedded/bundled code copies, so I'm planning to link OpenJK in Debian contrib to the system zlib. It seems better to use headers that correspond exactly to the system zlib, rather than the header that is bundled in OpenJK.

(This also means I can delete the zlib directory entirely in the Debian package, to know for sure that I'm not using the bundled copy and reduce the number of things I have to do a copyright/license audit on...)

### CODE REVIEW

**Comment by smcv** [comment]
This has some trivial conflicts with #604, so if you want to merge both this and #604, please either resolve the conflict manually, or pull smcv/OpenJK@8afd12f (my `system-libjpeg-and-zlib` branch) instead.

**Comment by ensiform** [comment]
Would rather not have to do any sort of manual merging from prs to accept it.

**Comment by smcv** [comment]
If you intend to merge #604, I'm happy to replace this PR with the appropriate branch; or if you don't intend to merge #604 for whatever reason, this one is mergeable. Sorry, I can't provide branches for both possibilities without making assumptions about what you're going to do next :-)

**Comment by ensiform** [comment]
Both are fine.

**Comment by smcv** [comment]
OK, I've replaced the branch for this PR with one that contains both. I'll close #604 as a duplicate or something.

**Pull request merged**
