### PR TITLE
Avoid double promotion via math functions

### PR DESCRIPTION
**Pull request by ShFil119**
it *should* help with vectorization. ;)

### CODE REVIEW

**Comment by ensiform** [comment]
Double promotion functions are more well supported in older versions of VS and ensure that there isn't going to be sneaky unexpected precision changes from vanilla whenever possible though.

**Comment by ShFil119** [comment]
So you prefer moving to c++ (`std::` overloaded for each type) or avoiding this changes?

**Comment by ensiform** [comment]
Certainly not. The mp sdk is C

**Comment by ShFil119** [comment]
I've seen issue about performance on rpi 3. (probably it was on forum) 
Comparing to gaining performance via diving tasks into threads, which requires significant changes in engine. This is almost *free*.

//btw I've seen large number of double consts, which can also cause promotion.

**Pull request closed without merging**
