### PR TITLE
ROFF2 bug fixes (#1002, #1003) and additional ROFF2 enhancments for SP

### PR DESCRIPTION
**Pull request by Archangel35757**
Fixes SP ROFF2 bugs: #1002 and #1003.
ROFF2 Notetracks have the form: \<type\> \<argument\> \<addlArg\>
ROFF2 Background: Original SP game only supported two ROFF2 Notetrack types: "effect" and "sound" ...while MP has a Notetrack type called "loop" (where it looped the ROF file relative to last current position). And SoF2 has an additional Notetrack type called "USE <IBI_ScriptName>".
ROFF2 Enhancements:
Type: "loop"
I expanded Notetrack type "loop" to have two argument options: < rof | sfx >.
"loop rof <relative | absolute>" -- will loop the rof in relative (loop at current pos) or absolute position (loop and move entity back to original starting position).
"loop sfx <soundfilepath>" -- adds a looping sound to the entity.

Type: "USE"
e.g.: "USE < IBI_scriptname_noExt >"
I added this Notetrack type that will specify to play an IBI script at the designated .ROF frame. This is untested but should work.

Type:"play"
I plan to add a new Notetrack type with format: "play <argument> <addlArg>" for example:
"play anim BOTH_STAND1" -- this will play the designated animation on a misc_model_ghoul entity. If it cannot find the animation, it defaults to trying to play the specified startFrame & endFrame.
This required minor changes to the SP_misc_model_ghoul entity function. The coding for this "play" Notetrack is in progress. I also intend to add support for this new "play" Notetrack to misc_model_breakable.

UPDATE:  The new ROFF2 Notetrack type "play" for misc_model_ghoul animations now compiles--  but is still undergoing debugging.

Test Case Files:
[rofftest_loop_rof-sfx_test.zip](https://github.com/JACoders/OpenJK/files/3048075/rofftest_loop_rof-sfx_test.zip)
[rofftest_loop_sfx_test.zip](https://github.com/JACoders/OpenJK/files/3048076/rofftest_loop_sfx_test.zip)
[rofftest_multi-notes-per-frame.zip](https://github.com/JACoders/OpenJK/files/3048077/rofftest_multi-notes-per-frame.zip)
[rofftest_original.zip](https://github.com/JACoders/OpenJK/files/3048078/rofftest_original.zip)
[shuttlemap.zip](https://github.com/JACoders/OpenJK/files/3050923/shuttlemap.zip)

### CODE REVIEW

**Comment by xycaleth** [comment]
We might want to rethink this pull request... you shouldn't be creating the pull request from your `master` branch since every commit you make will end up showing up in this pull request, even if it's unrelated.

**Comment by Archangel35757** [comment]
@xycaleth - so you would like me to create another Branch from history and isolate all of my ROFF2 changes?

**Comment by Archangel35757** [comment]
This is not ready!  Still debugging new notetrack type for bolting EFX onto Ghoul models.

**Comment by Archangel35757** [comment]
My enhancements break load/save compatibility.  Closing this request.  Will create a clean branch to submit bug fixes.

**Pull request closed without merging**
