### PR TITLE
Shared: fixed terminal mode and signal handlers on unix

### PR DESCRIPTION
**Pull request by ouned**
without this atty mode is always disabled on unix and command history
doesn't work

### CODE REVIEW

**Comment by xycaleth** [comment]
Looks good :) Thanks for the fix @ouned!

**Comment by ensiform** [comment]
CON_Init was before platform init on purpose.

Also, there is a proper signal handler function already.  Just needs to be hooked up in main().

As for the atty check, I'm not even sure it's required because the console handling works fine in ioq3 without it or did we miss something else in port of sys code?

**Comment by ouned** [comment]
https://github.com/ioquake/ioq3/blob/master/code/sys/sys_unix.c#L809

Didn't work for me without Con_Init after PlatformInit because Con_Init uses stdinIsATTY
ioq3 has PlatformInit before Con_Init, too

**Comment by ensiform** [comment]
I know, I moved it before because it technically needs to be initialized really early for the windows conosle to be set up properly for printing.

**Pull request merged**
