### PR TITLE
My fork is way out of date

### PR DESCRIPTION
**Pull request by dusty22**
I'm trying to update my code set with the latest changes from OpenJK, however my lack of knowledge of GitHub is making this difficult. I was trying to see a side-by-side comparison of whether any of my commits on my side conflict with newer OpenJK code files, however GitHub doesn't seem to want to show a side-by-side comparison. It only shows me things I've changed since the last time I pulled from the main OpenJK project...

Any help understanding the proper way to review this would be greatly appreciated :)

### CODE REVIEW

**Comment by dusty22** [comment]
Shiznet. I want to pull FROM JACoders into my fork, not the other way around. Tsk tsk tsk. Sorry.

**Comment by dusty22** [comment]
I'm leaving this open for a second, not because I want you guys to pull from me but just so someone can comment and help me clear a wee bit of my own confusion.

**Comment by dusty22** [comment]
Ack. I'm going to try and figure it out on my own.

**Comment by dionrhys** [comment]
Best way is to just ensure all your local changes are committed first so you have a clean working directory. Then simply pull the latest changes onto your branch (git pull). If there were no conflicts, you the merge will be successful. If there were any, it will say so and place markers in your files where the conflicts are. If you don't want to continue with a pull/merge, just do git merge --abort.

Open a thread on JKHub if need more assistance.

**Pull request closed without merging**
