### PR TITLE
Add the OpenJK icon's source material, released under the MIT/X11 license

### PR DESCRIPTION
**Pull request by smcv**
With permission from the artist, Antonio Aiello <http://tristamus.com>.

Related to JACoders/OpenJK#628, JACoders/OpenJK#630.

### CODE REVIEW

**Comment by smcv** [comment]
If you don't like `shared/icon` feel free to move it somewhere else... but I wanted to get a PR with the licensing info ready as soon as I could.

**Comment by xycaleth** [comment]
I feel like we need a separate folder for the icons to make it clear that the folder doesn't have any source code. Something like, `/resources/icons/` perhaps?

**Comment by smcv** [comment]
Sure, whatever you like. But if you wouldn't mind merging this first and moving things around later, I think all the pieces are in place for me to take a snapshot of the git repo and do the first fully DFSG-clean Debian packages for this stuff :-)

**Comment by smcv** [comment]
`/resources/icon/`, `/data/icon/`, `/shared/icon/`, or any of those with `icons` instead of `icon` all seem perfectly reasonable places to put this. Any is fine.

I would suggest not following ioquake3's example - `/misc/` is not the most self-describing directory name! I would also suggest avoiding `/assets/` so people don't think "wait, isn't `assets0.pk3` non-distributable?" and worry that it contains some of that stuff.

Potential future work (which I might do one day): make the build system use these icons instead of the ones in OS-specific directories, possibly moving `OpenJK.icns` into the same place as the `.psd` source. But for now the source files (and their resized versions) are just shipped as source and not hooked up to the build system at all.

**Comment by xycaleth** [comment]
Sounds reasonable!

**Pull request merged**
