### PR TITLE
Fix footprint rotation in SP #831

### LINKED ISSUE #831: Footprints aren't drawn with the correct rotation
**Operating system and version:**
OS X 10.11

**Is this for single player or multiplayer?**
Multiplayer

**Description of the bug (and if possible, steps to reproduce the bug):**
Footprints created from walking on sand aren't drawn at the correct rotation. They appear to be at 90-degrees to what it's supposed to be:
Footstep drawn badly

**What did you expect to happen instead?**
Footprints should be draw in the same direction as the one the player is walking in.

### PR DESCRIPTION
**Pull request by TwelveEyes**
Fixes #831 in sp. No reason to rotate footprints by 90 degrees.

### CODE REVIEW

**Review by ensiform — APPROVED** [review]

**Review by Razish — APPROVED** [review]

**Comment by bartrpe** [comment]
merg pls? @Razish

**Comment by TwelveEyes** [comment]
Is this good to merge?

**Comment by bartrpe** [comment]
> Is this good to merge?

yez plz merg

**Review by xycaleth — APPROVED** [review]
Is good! But I wonder why this works in the retail game and not here?

**Pull request merged**
