### PR TITLE
Enable macOS ARM64 build

### PR DESCRIPTION
**Pull request by JunielKatarn**
Adds the necessary macro checks to build for macOS/ARM64 out of the box.

### CODE REVIEW

**Comment by ensiform** [comment]
Since when is aarch64 big endian?

**Comment by JunielKatarn** [comment]
> Since when is aarch64 big endian?

My bad. Fixing.

**Comment by JunielKatarn** [comment]
@ensiform the project builds successfully producing *arm64* macOS binaries.

Is this good enough to merge?

**Comment by vorot93** [comment]
Also related to #1115

**Comment by Daggolin** [comment]
Not sure why `codeJK2/game/bg_pmove.cpp` was changed, but this PR seems to be similar to #1115, which was obsoleted by #1164.

**Pull request closed without merging**
