### PR TITLE
PR 848 fix

### PR DESCRIPTION
**Pull request by bibendovsky**
Fixes GCC compiling errors and warnings for #848.

### CODE REVIEW

**Comment by xycaleth** [comment]
Closing and reopening to see if I can get travis integration working.

**Comment by ensiform** [comment]
One nice thing about these improvements is that it allows friendlier modding in SP while allowing flexibility of save game changes needed or not.

**Comment by ensiform** [comment]
So I know this fixes saves running in 64 bit, but I forget if there is 32<>64 interoperability now?

**Comment by bibendovsky** [comment]
Yes, it works for both architectures.
Sorry for unfortunate PR original name :)

**Comment by ensiform** [comment]
What I was meaning to say was, 64 bit loads 32 bit saves and 32 bit can load 64 bit saves?

**Comment by bibendovsky** [comment]
Loading and saving does not depend on architecture. Saved game compatible with a vanilla one.

**Pull request merged**
