### PR TITLE
List of prohibition of sharing

### PR DESCRIPTION
**Pull request by Stalinsky1337RUSUKR**
hHello ,

Today i open the list of prohibition addresses 

currently use on 3 UKR/RUS FFA server

This addresses are not allowed by players due to policy violations. We open so all server use today 🎉 😄

### CODE REVIEW

**Comment by ensiform** [comment]
Umm there are no actual changes and I don't know what it is you are offering.  IP banning can be gotten around with VPNs.

**Comment by ensiform** [comment]
Just create a ban file that can be shared, that would be better option.

**Comment by Stalinsky1337RUSUKR** [comment]
he changed, but maybe it's too big? i see change and works on server

ban file is limit, but code is not limit

also we have anti vpn, i share later 😉 

i keep list update all months!please accept

**Comment by Stalinsky1337RUSUKR** [comment]
@ensiform

**Comment by Stalinsky1337RUSUKR** [comment]
@Razish

**Comment by Stalinsky1337RUSUKR** [comment]
@xycaleth

**Comment by Stalinsky1337RUSUKR** [comment]
@eezstreet

**Comment by ensiform** [comment]
Your code is in russian and it has caused the entire file to be "changed"  The line changes do not appear because of it.  I cannot accept this anyway, because as I said you can release a banlist file that uses the internal engine banlist functionality with all of the IPs that is not limited like the old addip method.

**Pull request closed without merging**
